cı pipeline update

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -44,5 +44,18 @@ jobs:
           echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
           echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
 
+      - name: Wait for Database to be Ready
+        run: |
+            echo "Waiting for database to be ready..."
+            for i in {1..10}; do
+              nc -zv localhost 5432 && echo "Database is ready!" && exit 0
+              echo "Database is not ready yet... retrying in 5s"
+              sleep 5
+            done
+            echo "Database failed to start in time."
+            exit 1
+            
       - name: Run Tests
         run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner
+
+        
