test dosyaları eklendi

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,11 +1,11 @@
-name: Run Tests
+name: CI/CD Pipeline
 
 on:
-  pull_request:
+  push:
     branches:
       - develop
       - main
-  push:
+  pull_request:
     branches:
       - develop
       - main
@@ -17,6 +17,14 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
+
+      - name: Cache Docker layers
+        uses: actions/cache@v3
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-docker-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-docker-
 
       - name: Set up Docker
         run: |
@@ -31,7 +39,7 @@ jobs:
       - name: Generate go.sum file
         run: go mod tidy
 
-      - name: Create .env file 
+      - name: Create .env file
         run: |
           echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
           echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
@@ -41,8 +49,21 @@ jobs:
           echo "DB_SSLMODE=disable" >> .env
         shell: bash
 
-      - name: Check if .env exists  # Debugging için
-        run: cat .env
-
       - name: Run Tests
         run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner
+
+      - name: Run Unit Tests with Coverage
+        run: gotestsum --format standard-verbose --junitfile report.xml ./...
+
+      - name: Publish Test Results
+        uses: actions/upload-artifact@v3
+        with:
+          name: test-results
+          path: report.xml
+
+      - name: Fail if Tests Fail
+        run: |
+          if grep -q "FAIL" report.xml; then
+            echo "Tests failed! Stopping build."
+            exit 1
+          fi
